# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #vmImage: 'ubuntu-latest'
  vmImage: 'vs2017-win2016'
  



steps:
    
- script: |
    nuget restore
    cd ExcelReader
    dotnet run

  displayName: 'Run a multi-line script'
